# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Joshua Herkness
tagline:          Blog
url:              www.joshherkness.com
paginate:         5
baseurl:          /
author:
  name:           Joshua Herkness
  url:            www.joshherkness.com
  email:          jrherkness@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
  
# Markdown
markdown: redcarpet
